### ISSUE TITLE
Bumper Borbs

### ISSUE THREAD

**Issue by Amaruuk** [kettek/litch#7]
BRB minigame wherein chat members select a borb which represents them to bounce around like a DVD logo amongst others on the screen.

Needs:
- chat command for chat members to join
- some kind of way for them to choose a borb or else have one assigned to them
- borbs should squish bouncily when hitting each other or the sides of the screen

IDK if there are any other features but those are what I've got in my head.

**Comment by kettek** [comment]
fin
